### ISSUE TITLE
Option to include terraform build script

### ISSUE THREAD

**Issue by peterkeating** [EtchUK/Etch.OrchardCore.SiteBoilerplate#14]
@lawrencedine has done some amazing work with creating our hosting infrastructure for running Orchard Core on Azure via [Terraform](https://www.terraform.io/). It would be great if this could be optionally included when creating a new site via this template instead of encouraging copy/pasting from other projects.

Whether this should be enabled by default would be an interesting discussion.

**Comment by JoeBerkley** [comment]
I don't see a reason for it not to be enabled by default, as in our own projects I believe we'll want this on pretty much every project. Plus if one is not needed but is accidentally generated you can just delete the file, which is a lot easier than the reverse, of wanting one and not generating it.

Expanding this, when we start supporting other providers, such as our next one we'll probably tackle in AWS, it would be good to provide options for those, but defaulting to Azure.

**Comment by lawrencedine** [comment]
Added by #17
