### ISSUE TITLE
Include instructions for what needs to be configured in Azure before running terraform

### ISSUE THREAD

**Issue by mobinzk** [EtchUK/Etch.OrchardCore.SiteBoilerplate#25]
I was setting up the devops CD on a project and found the [readme](https://github.com/EtchUK/Etch.OrchardCore.SiteBoilerplate/tree/master/Content/deployment/terraform/azure) could be improved.

Would be good to see the steps I need to do before running the terraform such as. Name of service plan, Name of SQL Server, Name of resource group and Client ID, Secret Key related to Let's Encrypt.

**Comment by peterkeating** [comment]
We'll be adding this to the internal Wiki so going to close this for now.
