### ISSUE TITLE
Include default ThemeBoilerplate theme

### ISSUE THREAD

**Issue by lawrencedine** [EtchUK/Etch.OrchardCore.SiteBoilerplate#34]
It may be useful to include the default theme boilerplate theme from nuget once https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/pull/96 is completed.

**Comment by JoeBerkley** [comment]
It looks like @peterkeating [has done this](https://github.com/EtchUK/Etch.OrchardCore.SiteBoilerplate/commit/62cd9eaa966452c3fe54c73fc7523073b9c34ff7)
