### ISSUE TITLE
DevOps pipeline yaml for Infrastructure

### ISSUE THREAD

**Issue by lawrencedine** [EtchUK/Etch.OrchardCore.SiteBoilerplate#35]
Having a pipeline `yaml` for the infrastructure stage which executes the Terraform scripts would be invaluable for site set up speed.

**Comment by peterkeating** [comment]
Closing as there doesn't appear to be a way to create release pipelines using `yaml`. Looks like we could create a template within dev ops that would also make it easy to setup a stage within an "Infrastructure" pipeline.

**Comment by PhilDye** [comment]
Do the newer "multi-stage pipelines" help address this? 
https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/environments?view=azure-devops
