### ISSUE TITLE
Application Insights

### ISSUE THREAD

**Issue by JoeBerkley** [EtchUK/Etch.OrchardCore.SiteBoilerplate#54]
During one of our meetings it came up that we should at the very least consider using application insights going forward, so if we're going into it, we'll need to have it added in to this boilerplate

**Comment by peterkeating** [comment]
Looks like we could create the application insights resource with terraform but linking it to the web app isn't possible.

https://github.com/terraform-providers/terraform-provider-azurerm/issues/1303

**Comment by PhilDye** [comment]
Creating the portal wiring may not be fully supported by terraform, but _using_ AppInsights should still be implemented. Provided the resource is created, nuget packages are added to the project, configured with a `APPINSIGHTS_INSTRUMENTATIONKEY` (and don't forget the frontend tag too), instrumentation will work.
